### PR TITLE
Add GitHub fork ribbon

### PR DESCRIPTION
**Pull request by hugovk**

### CODE REVIEW

**Comment by hugovk** [comment]
Merge conflict resolved.

You can see how the ribbon looks here: https://hugovk.github.io/bothub.org/html/

**Comment by non** [comment]
Thanks! I have to admit I'm slightly torn about adding a fancy high-tech ribbon on this very low-tech site :wink: 

Let me give it some thought -- I promise to get back to this soon.

**Comment by hugovk** [comment]
To make it look more low-tech, I've removed the drop shadow and stitching, and removed the font so it uses the same monospace, and made the colours match the page:

https://hugovk.github.io/bothub.org/html/

**Comment by non** [comment]
Wow that looks so great! Merging now. Thanks!

**Pull request merged**
